const ENDPOINT="https://cvwkvwvdtvmhlqpdyojn.supabase.co/functions/v1/freefire-sensitivity-v4";
const intro=document.querySelector("#intro");
const loader=document.querySelector("#loader");
const app=document.querySelector("#app");

const setStatus=(text)=>{
  const status=document.querySelector("#status");
  if(status) status.textContent=text;
};

document.querySelector("#enterBtn").onclick=()=>{
  intro.classList.add("hidden");
  loader.classList.remove("hidden");
  setTimeout(()=>{
    loader.classList.add("hidden");
    app.classList.remove("hidden");
  },900);
};

document.querySelector("#form").addEventListener("submit",async e=>{
  e.preventDefault();

  const btn=document.querySelector("#askBtn");
  const result=document.querySelector("#result");

  btn.disabled=true;
  btn.textContent="ANALYZING...";
  result.classList.add("hidden");
  setStatus("Connecting to AI...\nGemini → Groq API 2 → Groq API 3");

  const payload={
    device_name:document.querySelector("#device").value.trim(),
    player_style:document.querySelector("#style").value,
    graphics:document.querySelector("#graphics").value,
    language:document.querySelector("#language").value.trim()||"English"
  };

  if(!payload.device_name){
    setStatus("Please enter your device name.");
    btn.disabled=false;
    btn.textContent="GET AI SENSITIVITY";
    return;
  }

  const controller=new AbortController();
  const timeout=setTimeout(()=>controller.abort(),30000);

  try{
    const response=await fetch(ENDPOINT,{
      method:"POST",
      mode:"cors",
      cache:"no-store",
      headers:{
        "Content-Type":"application/json",
        "Accept":"application/json"
      },
      body:JSON.stringify(payload),
      signal:controller.signal
    });

    const raw=await response.text();
    let data=null;

    try{
      data=raw?JSON.parse(raw):null;
    }catch{
      throw new Error(`Server returned non-JSON (${response.status}): ${raw.slice(0,300)}`);
    }

    if(!response.ok){
      const details=Array.isArray(data?.details)
        ? data.details.map(x=>`${x.provider||"provider"}: ${x.error||"unknown error"}`).join("\n")
        : "";

      throw new Error([
        data?.error||`HTTP ${response.status} ${response.statusText}`,
        details,
        data?.configuration
          ? `Configuration: Gemini=${data.configuration.gemini}, Groq2=${data.configuration.groq2}, Groq3=${data.configuration.groq3}`
          : ""
      ].filter(Boolean).join("\n"));
    }

    if(!data?.reply){
      throw new Error("The AI function responded successfully, but no reply was returned.");
    }

    result.textContent=data.reply;
    result.classList.remove("hidden");

    setStatus(
      `Generated by ${data.provider||"AI"}`+
      (data.saved?" • saved to Supabase":"")+
      (data.failoverErrors?.length?" • fallback was checked":"")
    );

  }catch(error){
    let message=error?.message||"Unknown error";

    if(error?.name==="AbortError"){
      message="Request timed out after 30 seconds. The AI provider may be slow or unavailable.";
    }else if(message.includes("Failed to fetch")){
      message="Network/CORS error: the browser could not reach the Supabase Edge Function. Check the function URL, CORS response, and internet connection.";
    }

    setStatus(`AI request failed:\n${message}`);
  }finally{
    clearTimeout(timeout);
    btn.disabled=false;
    btn.textContent="GET AI SENSITIVITY";
  }
});
