const ENDPOINT="https://cvwkvwvdtvmhlqpdyojn.supabase.co/functions/v1/freefire-sensitivity-v5";
const intro=document.querySelector("#intro");
const loader=document.querySelector("#loader");
const app=document.querySelector("#app");

const setStatus=(text)=>{
  const status=document.querySelector("#status");
  if(status) status.textContent=text;
};

const val=id=>document.querySelector(id)?.value?.trim()||"";

document.querySelector("#enterBtn").onclick=()=>{
  intro.classList.add("hidden");
  loader.classList.remove("hidden");
  setTimeout(()=>{
    loader.classList.add("hidden");
    app.classList.remove("hidden");
  },700);
};

document.querySelector("#form").addEventListener("submit",async e=>{
  e.preventDefault();
  const btn=document.querySelector("#askBtn");
  const result=document.querySelector("#result");

  btn.disabled=true;
  btn.textContent="VERIFYING DEVICE...";
  result.classList.add("hidden");
  setStatus("Checking verified device registry...");

  const payload={
    device_name:val("#device"),
    ram_gb:val("#ram"),
    refresh_rate_hz:val("#refresh"),
    touch_sampling_hz:val("#touch"),
    dpi:val("#dpi"),
    width_px:val("#width"),
    height_px:val("#height"),
    game:val("#game"),
    game_version:val("#gameVersion"),
    fps:val("#fps"),
    player_style:val("#style"),
    graphics:val("#graphics"),
    calibration:val("#calibration"),
    language:val("#language")||"English"
  };

  const controller=new AbortController();
  const timeout=setTimeout(()=>controller.abort(),35000);

  try{
    setStatus("Checking verified device registry...\nThen Gemini → Groq API 2 → Groq API 3");
    const response=await fetch(ENDPOINT,{
      method:"POST",
      mode:"cors",
      cache:"no-store",
      headers:{"Content-Type":"application/json","Accept":"application/json"},
      body:JSON.stringify(payload),
      signal:controller.signal
    });

    const raw=await response.text();
    let data=null;
    try{data=raw?JSON.parse(raw):null}
    catch{throw new Error(`Server returned non-JSON (${response.status}): ${raw.slice(0,300)}`)}

    if(!response.ok){
      if(data?.error==="DEVICE_NOT_VERIFIED"){
        setStatus("❌ DEVICE NOT VERIFIED");
        result.textContent=`${data.message}\n\n${data.suggestion||""}`;
        result.classList.remove("hidden");
        return;
      }
      if(data?.error==="DEVICE_NOT_RELEASED"){
        setStatus("⏳ DEVICE NOT RELEASED");
        result.textContent=`${data.message}\n\nRegistered release date: ${data.device?.release_date||"unknown"}`;
        result.classList.remove("hidden");
        return;
      }
      const details=Array.isArray(data?.details)
        ? data.details.map(x=>`${x.provider||"provider"}: ${x.error||"unknown error"}`).join("\n")
        : "";
      throw new Error([data?.error||`HTTP ${response.status}`,details].filter(Boolean).join("\n"));
    }

    if(!data?.reply) throw new Error("The AI function returned no reply.");

    const d=data.device||{};
    const b=data.baseline||{};
    const header=[
      `VERIFIED DEVICE: ${d.name||payload.device_name}`,
      `Status: ${data.device_status||"verified_released"}`,
      `Release: ${d.release_date||"unknown"}`,
      `RAM: ${d.ram_gb??"unknown"} GB • Resolution: ${d.resolution||"unknown"}`,
      `Refresh: ${d.refresh_rate_hz??"unknown"} Hz • Touch: ${d.touch_sampling_hz??"unknown"} Hz`,
      `DPI: ${d.dpi??"unknown"} • Chipset: ${d.chipset||"unknown"}`,
      "",
      `DETERMINISTIC BASELINE`,
      `General: ${b.general??"-"}`,
      `Red Dot: ${b.red_dot??"-"}`,
      `2x: ${b.scope_2x??"-"}`,
      `4x: ${b.scope_4x??"-"}`,
      `Sniper: ${b.sniper??"-"}`,
      `Free Look: ${b.free_look??"-"}`,
      `Confidence: ${b.confidence||"unknown"}`,
      "",
      "AI ANALYSIS",
      data.reply
    ].join("\n");

    result.textContent=header;
    result.classList.remove("hidden");
    setStatus(`Generated by ${data.provider||"AI"} • ${data.saved?"saved to Supabase":"DB save failed"}`);
  }catch(error){
    const message=error?.name==="AbortError"
      ?"Request timed out after 35 seconds."
      :error?.message||"Unknown error";
    setStatus(`AI request failed:\n${message}`);
  }finally{
    clearTimeout(timeout);
    btn.disabled=false;
    btn.textContent="GET V5 AI SENSITIVITY";
  }
});
