const ENDPOINT="https://cvwkvwvdtvmhlqpdyojn.supabase.co/functions/v1/freefire-sensitivity-v4";
const intro=document.querySelector("#intro");
const loader=document.querySelector("#loader");
const app=document.querySelector("#app");

document.querySelector("#enterBtn").onclick=()=>{
  intro.classList.add("hidden");
  loader.classList.remove("hidden");
  setTimeout(()=>{
    loader.classList.add("hidden");
    app.classList.remove("hidden");
  },900);
};

document.querySelector("#form").addEventListener("submit",async e=>{
  e.preventDefault();

  const btn=document.querySelector("#askBtn");
  const status=document.querySelector("#status");
  const result=document.querySelector("#result");

  btn.disabled=true;
  btn.textContent="ANALYZING...";
  result.classList.add("hidden");
  status.textContent="AI 1: Gemini → if unavailable, automatically trying Groq API 2 → Groq API 3...";

  try{
    const payload={
      device_name:document.querySelector("#device").value.trim(),
      player_style:document.querySelector("#style").value,
      graphics:document.querySelector("#graphics").value,
      language:document.querySelector("#language").value.trim()||"English"
    };

    const response=await fetch(ENDPOINT,{
      method:"POST",
      headers:{"Content-Type":"application/json"},
      body:JSON.stringify(payload)
    });

    const data=await response.json();

    if(!response.ok){
      const details=Array.isArray(data.details)
        ? data.details.map(x=>`${x.provider}: ${x.error}`).join("\n")
        : "";
      throw new Error([data.error,details].filter(Boolean).join("\n"));
    }

    result.textContent=data.reply;
    result.classList.remove("hidden");

    status.textContent=
      `Generated by ${data.provider||"AI"}`+
      (data.saved?" • saved to Supabase":"")+
      (data.failoverErrors?.length?" • fallback was checked":"");

  }catch(error){
    status.textContent="AI request failed:\n"+(error?.message||"Unknown error");
  }finally{
    btn.disabled=false;
    btn.textContent="GET AI SENSITIVITY";
  }
});
